# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kqu6rpGvLfAFNEVXeIZTNY1EzGkCIAbu

**1. Load data**

Load the UCI "Predict Students' Dropout" dataset (697) via ucimlrepo — 4,424
students, 36 features, target = Dropout/Enrolled/Graduate.
"""

!pip install ucimlrepo -q

from ucimlrepo import fetch_ucirepo
import pandas as pd

ds = fetch_ucirepo(id=697)
X = ds.data.features
y = ds.data.targets.iloc[:, 0]   # Target column

df = X.copy()
df["Target"] = y
print(df.shape)
df.head()

"""**2. Class distribution**

Check how many students per class. Shows imbalance (Graduate ≫ Enrolled), which guides our metric choice later.
"""

import matplotlib.pyplot as plt
import seaborn as sns

print(y.value_counts())

sns.countplot(x=y, order=y.value_counts().index)
plt.title("Class distribution")
plt.xticks(rotation=15)
plt.show()

"""**3. Preprocessing**

Encode text labels to numbers, split 80/20 with stratify to keep class ratios, and scale features so models train properly.
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

le = LabelEncoder()
y_enc = le.fit_transform(y)   # dropout / enrolled / graduate -> 0,1,2

X_train, X_test, y_train, y_test = train_test_split(
    X, y_enc, test_size=0.2, stratify=y_enc, random_state=42
)

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

print("Classes:", list(le.classes_))
print("Train:", X_train.shape, "Test:", X_test.shape)

"""**4. Train models**

Train three classifiers — Logistic Regression, Decision Tree, Random Forest. class_weight="balanced" makes them handle the imbalance.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

models = {
    "Logistic Regression": LogisticRegression(max_iter=2000, class_weight="balanced"),
    "Decision Tree":       DecisionTreeClassifier(class_weight="balanced", random_state=42),
    "Random Forest":       RandomForestClassifier(class_weight="balanced", random_state=42),
}

for name, model in models.items():
    model.fit(X_train_s, y_train)
    print(f"{name} trained.")

"""**5. Evaluate**

Score each model on the test set with accuracy, precision, recall, F1 (macro average so every class counts equally). Compare in one table.
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

rows = []
for name, model in models.items():
    pred = model.predict(X_test_s)
    rows.append({
        "Model":     name,
        "Accuracy":  accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred, average="macro"),
        "Recall":    recall_score(y_test, pred, average="macro"),
        "F1":        f1_score(y_test, pred, average="macro"),
    })

results = pd.DataFrame(rows).set_index("Model").round(3)
results

"""**6. Best model detail**

Take the top-F1 model and view its per-class report and confusion matrix to see where it predicts well and where it confuses classes.
"""

from sklearn.metrics import confusion_matrix, classification_report

best_name = results["F1"].idxmax()
best_model = models[best_name]
pred = best_model.predict(X_test_s)

print("Best model:", best_name)
print(classification_report(y_test, pred, target_names=le.classes_))

cm = confusion_matrix(y_test, pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=le.classes_, yticklabels=le.classes_)
plt.xlabel("Predicted"); plt.ylabel("Actual")
plt.title(f"Confusion Matrix — {best_name}")
plt.show()

"""**7. Feature importance**

Rank which features the Random Forest relied on most — the strongest predictors of student outcome.
"""

rf = models["Random Forest"]
importances = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)

importances.head(10).plot(kind="barh")
plt.gca().invert_yaxis()
plt.title("Top 10 important features (Random Forest)")
plt.xlabel("Importance")
plt.show()